dist: xenial
sudo: required

language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential pkg-config check
  - sudo apt-get install -y autoconf automake libtool
  - sudo apt-get install -y libsndfile1-dev libsamplerate0-dev

script:
  - ./autogen.sh
  - make check
